// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4NfbjtliDLz7WregmwZR0PgoBod33lUQ',
    appId: '1:469819597131:web:5f6f3968fb80b3b0ecc8ce',
    messagingSenderId: '469819597131',
    projectId: 'nmims-25',
    authDomain: 'nmims-25.firebaseapp.com',
    storageBucket: 'nmims-25.firebasestorage.app',
    measurementId: 'G-EB76NHMSMD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD4EUe3_sXhvJbw-I_JvVKR7tq0jbNpa0s',
    appId: '1:469819597131:android:cf2027524c3839bcecc8ce',
    messagingSenderId: '469819597131',
    projectId: 'nmims-25',
    storageBucket: 'nmims-25.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD8al5lsqljEJE-aofWBkBYVEKxFruldGI',
    appId: '1:469819597131:ios:f9ad273b07ce5d17ecc8ce',
    messagingSenderId: '469819597131',
    projectId: 'nmims-25',
    storageBucket: 'nmims-25.firebasestorage.app',
    iosClientId: '469819597131-9nsm8rfgcf1i3kmn19f82rq7ddbaqmme.apps.googleusercontent.com',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD8al5lsqljEJE-aofWBkBYVEKxFruldGI',
    appId: '1:469819597131:ios:f9ad273b07ce5d17ecc8ce',
    messagingSenderId: '469819597131',
    projectId: 'nmims-25',
    storageBucket: 'nmims-25.firebasestorage.app',
    iosClientId: '469819597131-9nsm8rfgcf1i3kmn19f82rq7ddbaqmme.apps.googleusercontent.com',
    iosBundleId: 'com.example.myapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC4NfbjtliDLz7WregmwZR0PgoBod33lUQ',
    appId: '1:469819597131:web:5f6f3968fb80b3b0ecc8ce',
    messagingSenderId: '469819597131',
    projectId: 'nmims-25',
    authDomain: 'nmims-25.firebaseapp.com',
    storageBucket: 'nmims-25.firebasestorage.app',
    measurementId: 'G-EB76NHMSMD',
  );

}